package com.esbbank.gbo.xml.schemas.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-17T13:08:39.678+04:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", name = "DispatcherESBServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DispatcherESBServices {

    @WebMethod
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateCustomerMobileEmail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateCustomerMobileEmailFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAvailableTimes")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAvailableTimes(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAvailableTimesFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/scheduleManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply scheduleManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ScheduleManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createCustUserDefineValue")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createCustUserDefineValue(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateCustUserDefineValueFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateStatusDebitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateStatusDebitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateStatusDebitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/validateIBAN")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply validateIBAN(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ValidateIBANFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/pushMessage")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply pushMessage(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws PushMessageFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/validateAccount")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply validateAccount(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ValidateAccountFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateLimitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateLimitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateLimitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateCRSCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateCRSCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateCRSCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getServiceStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getServiceStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetServiceStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getFinanceDetails")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getFinanceDetails(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetFinanceDetailsFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cancelDDA")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cancelDDA(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CancelDDAFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/redeemFinance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply redeemFinance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RedeemFinanceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/limitInquiry")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply limitInquiry(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws LimitInquiryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getBusinessDay")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getBusinessDay(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetBusinessDayFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDebitCardTransList")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDebitCardTransList(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDebitCardTransListFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getReedeemStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getReedeemStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetReedeemStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/addPayee")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply addPayee(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws AddPayeeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateRIM")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateRIM(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateRIMFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/registerNewDebitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply registerNewDebitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RegisterNewDebitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCRSCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCRSCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCRSCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/checkCashRemittanceStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply checkCashRemittanceStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CheckCashRemittanceStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createCustomerOnBoard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createCustomerOnBoard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateCustomerOnBoardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/resetEPin")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply resetEPin(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ResetEPinFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDebitCardTheme")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDebitCardTheme(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDebitCardThemeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/registration")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply registration(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RegistrationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createBeneficiary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createBeneficiary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateBeneficiaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/newApplicationCreditCheckInquiry")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply newApplicationCreditCheckInquiry(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws NewApplicationCreditCheckInquiryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/generalPosting")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply generalPosting(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GeneralPostingFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/amendmentDDA")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply amendmentDDA(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws AmendmentDDAFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateBeneficiary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateBeneficiary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateBeneficiaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/makeBooking")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply makeBooking(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws MakeBookingFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createAccount")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createAccount(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateAccountFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cancelCashRemittance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cancelCashRemittance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CancelCashRemittanceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCustBehaviorScore")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCustBehaviorScore(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCustBehaviorScoreFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/payOrderManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply payOrderManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws PayOrderManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/generalTransfer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply generalTransfer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GeneralTransferFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/deletePayee")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply deletePayee(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws DeletePayeeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/initiateSIFUpload")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply initiateSIFUpload(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws InitiateSIFUploadFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/chequeSwiftIndicator")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply chequeSwiftIndicator(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ChequeSwiftIndicatorFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createNewCoverCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createNewCoverCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateNewCoverCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/validateEADIB")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply validateEADIB(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ValidateEADIBFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/financeClassInquiry")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply financeClassInquiry(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws FinanceClassInquiryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/enquireDDA")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply enquireDDA(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws EnquireDDAFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/deleteBeneficiary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply deleteBeneficiary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws DeleteBeneficiaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCustomerDetail")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCustomerDetail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCustomerDetailFaultMsg;

    @WebMethod(operationName = "OTPManagement", action = "urn:esbbank.com/gbo/xml/schemas/v1_0/OTPManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply otpManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws OTPManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getStatementHistory")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getStatementHistory(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetStatementHistoryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getUtilityList")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getUtilityList(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetUtilityListFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAccountTransactionList")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAccountTransactionList(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAccountTransactionListFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/inquireSalaryAdvance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply inquireSalaryAdvance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws InquireSalaryAdvanceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAccountChequeTrans")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAccountChequeTrans(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAccountChequeTransFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/makeFetchrBooking")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply makeFetchrBooking(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws MakeFetchrBookingFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getBankCurrency")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getBankCurrency(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetBankCurrencyFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getRimByMobileNumber")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getRimByMobileNumber(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetRimByMobileNumberFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAccountDetail")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAccountDetail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAccountDetailFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/utilityPayment")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply utilityPayment(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UtilityPaymentFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getLocation")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getLocation(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetLocationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/isCustomerExists")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply isCustomerExists(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws IsCustomerExistsFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateStatusCreditCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateStatusCreditCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateStatusCreditCardFaultMsg;

    @WebMethod(operationName = "PDCStatus", action = "urn:esbbank.com/gbo/xml/schemas/v1_0/PDCStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply pdcStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws PDCStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/dataUpload")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply dataUpload(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws DataUploadFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/riskAssessment")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply riskAssessment(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RiskAssessmentFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getFinanceStatement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getFinanceStatement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetFinanceStatementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/doDataScreening")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply doDataScreening(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws DoDataScreeningFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getTransStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getTransStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetTransStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCustAddressFromPrime")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCustAddressFromPrime(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCustAddressFromPrimeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/coverCardPinValidation")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply coverCardPinValidation(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CoverCardPinValidationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCustomerDetailsByRim")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCustomerDetailsByRim(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCustomerDetailsByRimFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/customerSearch")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply customerSearch(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CustomerSearchFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cardInquiry")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cardInquiry(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CardInquiryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getFetchrTimeSlots")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getFetchrTimeSlots(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetFetchrTimeSlotsFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/startSecurityChequeProcess")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply startSecurityChequeProcess(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws StartSecurityChequeProcessFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getEStatement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getEStatement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetEStatementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cb102Bulk")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cb102Bulk(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws Cb102BulkFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAccountByRim")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAccountByRim(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAccountByRimFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/validatePIN")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply validatePIN(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ValidatePINFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCardsLinkToAccount")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCardsLinkToAccount(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws Operation1FaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/registerDDA")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply registerDDA(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RegisterDDAFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDepositAcctHistory")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDepositAcctHistory(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDepositAcctHistoryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getPayees")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getPayees(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetPayeesFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/filenetManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply filenetManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws FilenetManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/retailBeneficiaryInq")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply retailBeneficiaryInq(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws RetailBeneficiaryInqFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cardDetail")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cardDetail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CardDetailFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/earlySettlement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply earlySettlement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws EarlySettlementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cardPayment")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cardPayment(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CardPaymentFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDDACodeList")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDDACodeList(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDDACodeListFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateSMSCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateSMSCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateSMSCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/needChequeBook")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply needChequeBook(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws NeedChequeBookFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getSalaryAdvace")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getSalaryAdvace(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetSalaryAdvaceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/accountQuery")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply accountQuery(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws AccountQueryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/sendEmail")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply sendEmail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SendEmailFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/checkStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply checkStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CheckStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createRIM")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createRIM(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateRIMFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/debitCardPinValidation")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply debitCardPinValidation(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws DebitCardPinValidationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getComplaintStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getComplaintStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetComplaintStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/utilityInquiry")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply utilityInquiry(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UtilityInquiryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/limitMaintenance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply limitMaintenance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws LimitMaintenanceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/incomingSWIFT")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply incomingSWIFT(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws IncomingSWIFTFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getTransferRate")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getTransferRate(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetTransferRateFaultMsg;

    @WebMethod(operationName = "VASCOManagement", action = "urn:esbbank.com/gbo/xml/schemas/v1_0/VASCOManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply vascoManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws VASCOManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateCustomerCompliance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateCustomerCompliance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateCustomerComplianceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/sellBackCommodity")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply sellBackCommodity(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SellBackCommodityFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/stopDDAPayment")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply stopDDAPayment(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws StopDDAPaymentFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/esbService")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply esbService(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws EsbServiceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/eStatementManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply eStatementManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws EStatementManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getRimByDebitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getRimByDebitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetRimByDebitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/checkStatusOnBoard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply checkStatusOnBoard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CheckStatusOnBoardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getMurabaContract")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getMurabaContract(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetMurabaContractFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateCreditCardLimit")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateCreditCardLimit(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateCreditCardLimitFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getEStatementInfo")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getEStatementInfo(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetEStatementInfoFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getChargesRequest")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getChargesRequest(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetChargesRequestFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getBeneficiaries")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getBeneficiaries(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetBeneficiariesServiceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/sendSMS")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply sendSMS(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SendSMSFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/transfer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply transfer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws TransferFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/linkDebitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply linkDebitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws LinkDebitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/editPayee")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply editPayee(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws EditPayeeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getBankDetail")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getBankDetail(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetBankDetailFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/setUpdateStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply setUpdateStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SetUpdateStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getSukukCertificate")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getSukukCertificate(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetSukukCertificateFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/updateCustomerInfo")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply updateCustomerInfo(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UpdateCustomerInfoFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/accountSummary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply accountSummary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws AccountSummaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/idValidate")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply idValidate(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws IdValidateFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getExpressFinanceEligibility")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getExpressFinanceEligibility(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetExpressFinanceEligibilityFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getRegisteredCustomers")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getRegisteredCustomers(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetRegisteredCustomersFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/standingOrderSummary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply standingOrderSummary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws StandingOrderSummaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDepositStatementHistory")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDepositStatementHistory(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDepositStatementHistoryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/validateSIF")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply validateSIF(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ValidateSIFFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getSIFStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getSIFStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetSIFStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getTransactionDetails")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getTransactionDetails(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetTransactionDetailsFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createEPin")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createEPin(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateEPinFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/paymentDetailsDDA")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply paymentDetailsDDA(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws PaymentDetailsFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/trandeAccountSummary")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply trandeAccountSummary(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws TrandeAccountSummaryFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/smsRegistration")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply smsRegistration(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SmsRegistrationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/holdTransaction")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply holdTransaction(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws HoldTransactionFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/manageSMSCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply manageSMSCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ManageSMSCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getCoreTransactionMode")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getCoreTransactionMode(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetCoreTransactionModeFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/chequeManagement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply chequeManagement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ChequeManagementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getADIBExpressBranch")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getADIBExpressBranch(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetADIBExpressBranchFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createDebitCard")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createDebitCard(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateDebitCardFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/exchangeRate")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply exchangeRate(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ExchangeRateFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/cardAutherization")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply cardAutherization(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CardAutherizationFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAvailableDates")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAvailableDates(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAvailableDatesFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getApplicationStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getApplicationStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetApplicationStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAlgoStatus")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAlgoStatus(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAlgoStatusFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/swiftAdviceDownload")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply swiftAdviceDownload(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SwiftAdviceDownloadFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/unsubscribeSMSCustomer")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply unsubscribeSMSCustomer(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws UnsubscribeSMSCustomerFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getDebitCardList")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getDebitCardList(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetDebitCardListFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getMortgageTransaction")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getMortgageTransaction(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetMortgageTransactionFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getAccountSalaryTrans")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getAccountSalaryTrans(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetAccountSalaryTransFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/saveMurabahaAgreement")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply saveMurabahaAgreement(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws SaveMurabahaAgreementFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/getFXRate")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getFXRate(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetFXRateFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/stpService")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply stpService(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws StpServiceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createCommodity")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createCommodity(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateCommodityFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/createCashRemittance")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply createCashRemittance(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws CreateCashRemittanceFaultMsg;

    @WebMethod(action = "urn:esbbank.com/gbo/xml/schemas/v1_0/releaseHoldTransaction")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply releaseHoldTransaction(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws ReleaseHoldTransactionFaultMsg;

    @WebMethod(operationName = "GetFXDeal", action = "urn:esbbank.com/gbo/xml/schemas/v1_0/GetFXDeal")
    @WebResult(name = "esbServiceReply", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/", partName = "esbServiceReply")
    public ESBServiceReply getFXDeal(
        @WebParam(partName = "esbServiceRequest", name = "esbServiceRequest", targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
        ESBServiceRequest esbServiceRequest
    ) throws GetFXDealFaultMsg;
}
