package com.esbbank.gbo.xml.schemas.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-23T14:48:31.977+04:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "DispatcherESBServicesHttpService",
                  wsdlLocation = "file:/Users/mahmutogrek/Documents/workspace-spring-tool-suite-4-4.3.0.RELEASE/ESBService/src/main/resources/ESBService_1.wsdl",
                  targetNamespace = "urn:esbbank.com/gbo/xml/schemas/v1_0/")
public class DispatcherESBServicesHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:esbbank.com/gbo/xml/schemas/v1_0/", "DispatcherESBServicesHttpService");
    public final static QName DispatcherESBServicesHttpPort = new QName("urn:esbbank.com/gbo/xml/schemas/v1_0/", "DispatcherESBServicesHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mahmutogrek/Documents/workspace-spring-tool-suite-4-4.3.0.RELEASE/ESBService/src/main/resources/ESBService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DispatcherESBServicesHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/mahmutogrek/Documents/workspace-spring-tool-suite-4-4.3.0.RELEASE/ESBService/src/main/resources/ESBService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DispatcherESBServicesHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DispatcherESBServicesHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DispatcherESBServicesHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DispatcherESBServicesHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DispatcherESBServicesHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DispatcherESBServicesHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DispatcherESBServices
     */
    @WebEndpoint(name = "DispatcherESBServicesHttpPort")
    public DispatcherESBServices getDispatcherESBServicesHttpPort() {
        return super.getPort(DispatcherESBServicesHttpPort, DispatcherESBServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DispatcherESBServices
     */
    @WebEndpoint(name = "DispatcherESBServicesHttpPort")
    public DispatcherESBServices getDispatcherESBServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(DispatcherESBServicesHttpPort, DispatcherESBServices.class, features);
    }

}
